# Generated by Django 2.2.2 on 2019-07-19 12:45

from django.db import migrations, models

from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),

        migrations.CreateModel(
            name='PasswordHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('hint', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
