# Generated by Django 2.2.2 on 2019-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhint',
            name='hint',
            field=models.CharField(default='', max_length=200),
        ),
    ]
