# Generated by Django 2.2.2 on 2019-07-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhint',
            name='hint',
            field=models.CharField(max_length=200),
        ),
    ]
